### ISSUE TITLE
Nondeterminism in misc/checksum

### ISSUE THREAD

**Issue by LordYuuma** [spk121/guile-gi#16] opened 2019-07-07 17:52 UTC
Every once in a blue moon, misc/checkum fails with a diffferent checksum. [It has happened on Travis](https://travis-ci.com/spk121/guile-gi/builds/118147575), so we ought to fix this.

**Comment by spk121** [comment] 2019-07-07 18:43
Under the hood, this is a duplicate of #15 
At the moment, introspected function's arguments that are non-zero-terminated arrays are incorrectly computing the array length.

**Comment by LordYuuma** [comment] 2019-07-07 18:48
But shouldn't it fail consistently then? The incorrect lengths should be pseudo-constants IIRC.

**Comment by spk121** [comment] 2019-07-07 19:02
At the moment, non-zero-terminated input bytevector arguments are failing over to being zero-terminated bytevectors, causing random effective array lengths.  It is just that those arrays are very often coincidentally zero terminated, so that the test often succeeds.

I'm almost done with #15, which, I believe, with fix this issue as well.

**Comment by spk121** [comment] 2019-07-11 05:56
Fixed by the merge of bd6a99472daa844bf3cd623bdef9c3ea39413f4f

**Closed by spk121** 2019-07-11 05:56 UTC
Labels: bug
